################################################################################
# Node-RED Stack or Compose
################################################################################
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up
################################################################################
version: "3.7"

services:
  node-red:
    build: .
    image: nodered/node-red:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Stockholm
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - node-red-data:/data
      - ./solaredge-modbus.json:/data/flows.json

volumes:
  node-red-data:

networks:
  node-red-net: